import type { Product } from "@/components/ui/ProductCard";

export const PRODUCTS: Product[] = [
  {
    title: "Posture Corrector Pro Belt",
    emoji: "🧍",
    image: "/images/products/posture-corrector.svg",
    stock: 4532,
    supplier: "Dropi",
    country: "Mexico",
    flag: "🇲🇽",
    price: "$5,450",
    sales: 554,
    trend: [3, 5, 4, 7, 6, 9, 8, 12, 11, 15, 17, 21],
  },
  {
    title: "Mini Portable Blender USB",
    emoji: "🥤",
    image: "/images/products/mini-blender.svg",
    stock: 2870,
    supplier: "Dropi",
    country: "Colombia",
    flag: "🇨🇴",
    price: "$3,200",
    sales: 731,
    trend: [4, 4, 6, 5, 8, 10, 9, 13, 14, 16, 19, 24],
  },
  {
    title: "LED Galaxy Star Projector",
    emoji: "🌌",
    image: "/images/products/galaxy-projector.svg",
    stock: 6190,
    supplier: "MasterShop",
    country: "United States",
    flag: "🇺🇸",
    price: "$8,990",
    sales: 1208,
    trend: [6, 7, 6, 9, 11, 10, 14, 16, 18, 21, 25, 29],
  },
  {
    title: "Magnetic Phone Mount 360°",
    emoji: "📱",
    image: "/images/products/phone-mount.svg",
    stock: 1845,
    supplier: "Shopify",
    country: "Chile",
    flag: "🇨🇱",
    price: "$2,150",
    sales: 423,
    trend: [2, 3, 5, 4, 6, 7, 9, 8, 11, 13, 14, 18],
  },
  {
    title: "Anti-Gravity Humidifier",
    emoji: "💧",
    image: "/images/products/humidifier.svg",
    stock: 3410,
    supplier: "Dropi",
    country: "Peru",
    flag: "🇵🇪",
    price: "$4,780",
    sales: 689,
    trend: [3, 4, 4, 6, 8, 7, 10, 12, 13, 15, 18, 22],
    tone: "pink",
  },
  {
    title: "Smart Pet Water Fountain",
    emoji: "🐾",
    image: "/images/products/pet-fountain.svg",
    stock: 5021,
    supplier: "MasterShop",
    country: "Mexico",
    flag: "🇲🇽",
    price: "$6,320",
    sales: 902,
    trend: [5, 6, 8, 7, 9, 11, 13, 12, 16, 18, 20, 26],
  },
  {
    title: "Foldable Sunset Lamp",
    emoji: "🌅",
    image: "/images/products/sunset-lamp.svg",
    stock: 2290,
    supplier: "Dropi",
    country: "Ecuador",
    flag: "🇪🇨",
    price: "$3,540",
    sales: 376,
    trend: [2, 2, 3, 5, 4, 7, 6, 9, 10, 12, 13, 16],
    tone: "pink",
  },
  {
    title: "Wireless Car Vacuum Kit",
    emoji: "🚗",
    image: "/images/products/car-vacuum.svg",
    stock: 4115,
    supplier: "Shopify",
    country: "United States",
    flag: "🇺🇸",
    price: "$7,150",
    sales: 815,
    trend: [4, 5, 7, 6, 9, 8, 12, 14, 15, 17, 21, 25],
  },
  {
    title: "Heated Eye Massage Mask",
    emoji: "😴",
    image: "/images/products/eye-massage-mask.svg",
    stock: 3680,
    supplier: "Dropi",
    country: "Argentina",
    flag: "🇦🇷",
    price: "$4,290",
    sales: 612,
    trend: [3, 4, 6, 5, 8, 9, 11, 10, 14, 16, 18, 23],
  },
  {
    title: "Electric Spin Scrubber Set",
    emoji: "🧽",
    image: "/images/products/spin-scrubber.svg",
    stock: 5540,
    supplier: "MasterShop",
    country: "Brazil",
    flag: "🇧🇷",
    price: "$5,980",
    sales: 1043,
    trend: [5, 7, 6, 10, 9, 13, 15, 14, 18, 20, 23, 28],
  },
];
